# Generated by Django 3.2 on 2021-05-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('categories', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('bpost', models.TextField()),
            ],
        ),
    ]
