# Generated by Django 3.2 on 2021-05-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_auto_20210506_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='bwholepost',
            field=models.TextField(default='description'),
        ),
    ]
