# Generated by Django 3.2 on 2021-05-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='coment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pro.blogpost'),
            preserve_default=False,
        ),
    ]
