# Generated by Django 3.2 on 2021-05-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_projects_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='link',
            field=models.URLField(default='https://www.linkedin.com/feed/'),
            preserve_default=False,
        ),
    ]
