# Generated by Django 3.2 on 2021-05-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_sharing_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='linkname',
            field=models.CharField(default='github', max_length=100),
        ),
    ]
