# Generated by Django 3.2 on 2021-05-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sharing_linkname'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='aboutme',
            field=models.TextField(default='abhishek'),
        ),
    ]
