# Generated by Django 3.2 on 2021-05-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_projects_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comments1', models.TextField()),
                ('coment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.projects')),
            ],
        ),
    ]
