# Generated by Django 3.2 on 2021-05-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments1',
            new_name='comment',
        ),
    ]
