# Generated by Django 3.2 on 2021-05-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=20)),
                ('rolname', models.CharField(max_length=300)),
                ('dateoc', models.DateTimeField()),
                ('disc', models.TextField()),
            ],
        ),
    ]
