# Generated by Django 3.2 on 2021-05-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selffp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unname', models.CharField(max_length=200)),
                ('degr', models.CharField(max_length=300)),
                ('datep', models.DateField()),
                ('disc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='carrer1',
            name='dateoc',
            field=models.DateField(),
        ),
    ]
