# Generated by Django 3.2 on 2021-05-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selffp', '0003_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='perc',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
