# Generated by Django 3.2 on 2021-05-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selffp', '0005_abouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouts',
            name='adfir',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouts',
            name='adsec',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouts',
            name='ema',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouts',
            name='finame',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouts',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
