# Generated by Django 3.2 on 2021-05-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selffp', '0006_auto_20210504_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=300)),
                ('dateofcompl', models.DateField()),
                ('linkofcertificate', models.URLField()),
            ],
        ),
    ]
