# Generated by Django 3.2 on 2021-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selffp', '0007_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('Name', models.CharField(max_length=200)),
                ('Profession', models.CharField(max_length=300)),
                ('Company_name', models.CharField(max_length=300)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
