  # Generated by Django 3.2 on 2021-05-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selffp', '0008_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(upload_to='image'),
        ),
    ]
