# Generated by Django 3.2 on 2021-05-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selffp', '0010_remove_testimonial_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='datep',
            field=models.DateField(null=True),
        ),
    ]
