# Generated by Django 3.2 on 2021-05-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selffp', '0011_alter_education_datep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='datep',
            field=models.DateField(blank=True, null=True),
        ),
    ]
